### PR TITLE
fix for v2.3 changes

### PR DESCRIPTION
**Pull request by IsaacHatton**
WIP please don't merge

Working on fixing #159, would appreciate any input from anyone else as well

So far fixed the menu icon, but my patch isn't backwards compatible for the old version that other people seem to have (seems to be an A/B test)

Much of the extension is still non-functional.

### CODE REVIEW

**Comment by IsaacHatton** [comment]
image
I think it might be moduleRaid (or at least the version that we use causing issues)

A more modern fork of moduleRaid produces an unknown Webpack structure error....
image

I have absolutely no idea how Webpack works, do you understand what these errors could mean @tomer8007?

**Comment by tomer8007** [comment]
Thank you for your effort.
Note that I patched moduleRaid here:
https://github.com/tomer8007/whatsapp-web-incognito/blob/4f092c9e4bb66982f496b8cc4d9f8427f304b300/lib/moduleraid.js#L14
The main question to ask is whether you have a global variable callled `webpackChunkwhatsapp_web_client`.

Also, is the interception working? Do the main features work somehow?

**Comment by IsaacHatton** [comment]
image

The only thing that works is read reciepts being blocked, but I haven't inputted the new classes to look for so there's no UI to send them.

I believe status downloading is unaffected though.

**Comment by tomer8007** [comment]
Looks like we need to find the new `webpackChunkwhatsapp_web_client`. Do they still use React?

**Comment by tomer8007** [comment]
I now managed to get version 2.3000. Will work on this too.

**Comment by tomer8007** [comment]
> Looks like we need to find the new webpackChunkwhatsapp_web_client.

They now have `__d`.

**Pull request closed without merging**
