### PR TITLE
Clarify in Dropdown: Typing status is also disabled

### PR DESCRIPTION
**Pull request by IsaacHatton**
I was confused by the text in the dropdown initially, I believe that this change will increase clarity as to the side effects of enabling this feature.

### CODE REVIEW

**Comment by tomer8007** [comment]
Thanks but this makes the menu a bit larger:

image

What do you think about also changing the text like this:

image
?

**Comment by IsaacHatton** [comment]
Yes, I think that also would improve it, apologies for not spotting the movement of the Next button.

I will make a commit now to change that text

**Comment by tomer8007** [comment]
How does it look like in your end?

**Comment by IsaacHatton** [comment]
image

**Pull request merged**
